<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>ShardEqualizer.Contracts</AssemblyName>
        <RootNamespace>ShardEqualizer.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Configs\" />
    </ItemGroup>
    
</Project>
