<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>ShardEqualizer</RootNamespace>
    <AssemblyName>ShardEqualizer</AssemblyName>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ShardEqualizer</ToolCommandName>
    <Authors>Anatoliy Koperin &lt;a.koperin@gmail.com&gt;</Authors>
    <Description>Tool for aligning the size of stored data on shards in a MongoDB cluster</Description>
    <RepositoryUrl>https://github.com/ExM/ShardEqualizer</RepositoryUrl>
    <PackageLicenseUrl>https://github.com/ExM/ShardEqualizer/blob/develop/LICENSE.txt</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/ExM/ShardEqualizer</PackageProjectUrl>
    <PackageTags>mongodb sharding</PackageTags>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <PackageVersion>2.0.0-beta.0</PackageVersion>
    <InformationalVersion>2.0.0-beta.0</InformationalVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Accord.Math" />
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="MongoDB.Bson" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="NConfiguration" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Ninject" />
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="configuration.sample.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dev.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caching\Caching.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\DAL\DAL.csproj" />
    <ProjectReference Include="..\ScriptGen\ScriptGen.csproj" />
    <ProjectReference Include="..\ShardedClusterViews\ShardedClusterViews.csproj" />
  </ItemGroup>
</Project>
